# Generated by Django 4.0.2 on 2022-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Hakkımızda')),
                ('about', models.TextField(max_length=300, verbose_name='Hakkımızda')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
