# Generated by Django 4.0.2 on 2022-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0002_comment_personel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('title', models.CharField(max_length=50, verbose_name='Tittle')),
                ('info', models.CharField(max_length=50, verbose_name='İnfo')),
            ],
        ),
    ]
