# Generated by Django 4.0.2 on 2022-05-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0004_referance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
