# Generated by Django 4.0.2 on 2022-05-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0005_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=300, verbose_name='Hakkımızda Sağ '),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Hakkımızda Sol '),
        ),
    ]
