# Generated by Django 4.0.2 on 2022-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0006_alter_about_about_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Titile'),
        ),
    ]
