# Generated by Django 4.0.2 on 2022-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0007_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Personel İsim'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Personel title'),
        ),
    ]
