# Generated by Django 4.0.2 on 2022-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0008_alter_personel_name_alter_personel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referance',
            name='title',
        ),
        migrations.AlterField(
            model_name='referance',
            name='referance',
            field=models.CharField(max_length=50, verbose_name='Referance İşletme'),
        ),
    ]
