# Generated by Django 4.0.2 on 2022-05-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0009_remove_referance_title_alter_referance_referance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Pozisyon'),
        ),
    ]
