# Generated by Django 4.0.2 on 2022-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0010_alter_comment_name_alter_comment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='referance',
            name='work',
            field=models.CharField(default=21, max_length=50, verbose_name='Yapılan İş'),
            preserve_default=False,
        ),
    ]
