# Generated by Django 4.0.5 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0011_referance_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='İlk Yazı')),
                ('header', models.CharField(max_length=20, verbose_name='Kalın Yazı')),
                ('info', models.CharField(max_length=20, verbose_name='Mini Açıklama')),
                ('linkone', models.CharField(max_length=20, verbose_name='Yönlendirilcek Sayfa 1')),
                ('linktwo', models.CharField(max_length=20, verbose_name='Yönlendirilcek Sayfa 2')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
