# Generated by Django 4.0.5 on 2022-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0012_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='header',
            field=models.CharField(max_length=200, verbose_name='Kalın Yazı'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='info',
            field=models.CharField(max_length=200, verbose_name='Mini Açıklama'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='İlk Yazı'),
        ),
    ]
