# Generated by Django 4.0.5 on 2022-07-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0013_alter_slider_header_alter_slider_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image4',
        ),
    ]
