# Generated by Django 4.0.5 on 2022-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0014_remove_about_image2_remove_about_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='Hakkımızda Sağ '),
        ),
    ]
