# Generated by Django 4.0.5 on 2022-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0016_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
