# Generated by Django 4.0.5 on 2022-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0017_alter_partners_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='referance',
            field=models.CharField(max_length=30, verbose_name='Referance İşletme'),
        ),
        migrations.AlterField(
            model_name='referance',
            name='work',
            field=models.CharField(max_length=30, verbose_name='Yapılan İş'),
        ),
    ]
