# Generated by Django 4.0.5 on 2022-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0018_alter_referance_referance_alter_referance_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='referance',
            field=models.CharField(max_length=50, verbose_name='Referance İşletme'),
        ),
        migrations.AlterField(
            model_name='referance',
            name='work',
            field=models.CharField(max_length=50, verbose_name='Yapılan İş'),
        ),
    ]
