# Generated by Django 4.0.5 on 2022-07-29 18:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0020_alter_service_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ability',
            field=models.CharField(default=21, max_length=150, verbose_name='Giriş Yapınız'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ability3',
            field=models.CharField(default=21, max_length=150, verbose_name='Giriş Yapınız'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ability4',
            field=models.CharField(default=21, max_length=150, verbose_name='Giriş Yapınız'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ability5',
            field=models.CharField(default=21, max_length=150, verbose_name='Giriş Yapınız'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ability6',
            field=models.CharField(default=21, max_length=150, verbose_name='Giriş Yapınız'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='header',
            field=models.CharField(default=21, max_length=500, verbose_name='Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='infoTwo',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=250, verbose_name='Mini Açıklama'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamaris.service')),
            ],
        ),
    ]
