# Generated by Django 4.0.5 on 2022-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0021_service_ability_service_ability3_service_ability4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
