# Generated by Django 4.0.5 on 2022-07-29 20:12

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0023_service_ability2_alter_service_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
