# Generated by Django 4.0.5 on 2022-07-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0025_youtube_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='video',
            new_name='url',
        ),
    ]
