# Generated by Django 4.0.5 on 2022-07-31 14:29

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamaris', '0026_rename_video_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='Hakkımızda'),
        ),
    ]
